services:
  - type: web
    name: shl-assessment-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: TOGETHER_API_KEY
        sync: false
